# Project identification
sonar.projectKey=spring-boot-demo
sonar.projectName=Spring Boot Quality Demo
sonar.sourceEncoding=UTF-8

sonar.token=yurayuno

sonar.login=arc
sonar.password=warden
# Source code locations
sonar.sources=src/main/java
sonar.tests=src/test/java

# Exclusions
sonar.exclusions=**/config/**,**/dto/**

# Java version
sonar.java.source=17
sonar.java.target=17

sonar.forceAuthentication=False