#useless
spring.application.name=Tempest Double

#MySQL config

spring.datasource.url=${SPRING_DATASOURCE_URL}/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional: Hibernate configuration for JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Enables color coded logs in console
spring.output.ansi.enabled = ALWAYS
#Defines the color code preserving spring logging style (date-thread-importance-source-message)
logging.pattern.console= %clr(%d{yyyy-MMM-dd HH:mm:ss.SSS}){green} [%thread] %highlight(%-5level) %magenta(%-40.40logger{39}) - %msg %n
